function [Vis_peri,Vis_peri_lb,Vis_peri_ub,Vis_core,Vis_core_lb,Vis_core_ub] =...
    CalVis_Peri_Core(delta_t,temp_K,probe_radius,spMap,contour_range, cell_outline, num_pix_y,...
    aspt_ratio,raw_spatialDisp,Simu_spatialDisp,acc_fit, Ro,Lo,anchor_spMap,...
    scaling_width,scaling_length, slack_Peri, slack_Core)

[coord_in_core, coord_in_peri, peri1, peri2] =...
    Nuc_Seg(spMap, contour_range,...
    cell_outline, num_pix_y, aspt_ratio, ["off" "off"]);

[Step_in_Core,~] =...
    Extract_Step_InRegion(raw_spatialDisp,...
    coord_in_core,num_pix_y,aspt_ratio);
[Step_in_Core_simu,~] =...
    Extract_Step_InRegion(Simu_spatialDisp,...
    coord_in_core,num_pix_y,aspt_ratio);

[Step_in_Peri,~] =...
    Extract_Step_InRegion(raw_spatialDisp,...
    coord_in_peri,num_pix_y,aspt_ratio);
[Step_in_Peri_simu,~] =...
    Extract_Step_InRegion(Simu_spatialDisp,...
    coord_in_peri,num_pix_y,aspt_ratio);

% weight ratio of periphery and core
[pop_peri_ratio,pop_core_ratio] = Pop_Peri_Core_Ratio(...
    5e5,acc_fit,Ro,Lo,anchor_spMap,scaling_width,...
    scaling_length,num_pix_y,aspt_ratio,{peri1,peri2});

[p_simu_peri,p_fit_peri,~,~,~,~] =...
    In_Nuc_fit(Step_in_Peri_simu,Step_in_Peri,...
    pop_peri_ratio,slack_Peri(1),slack_Peri(2),...
    (0:20:1000),["off" , "off"]);
p_peri_fit_ci = In_Nuc_fit_ci(Step_in_Peri,p_fit_peri);

% Physical properties derived from the fit
Diff_peri_um2s = p_fit_peri(2) / (4*delta_t) * 1e-3;            % µm²/s
Vis_peri    = 1.380649e-23*temp_K / (6*pi*probe_radius* ...
                   Diff_peri_um2s * 1e-12) * 1e3;          % cP
Vis_peri_lb = 1.380649e-23*temp_K/(6*pi*probe_radius*(p_peri_fit_ci(2)/(4*delta_t)*1e-3)*1e-12)*1e3; %cP (centipoise, mPa⋅s)
Vis_peri_ub = 1.380649e-23*temp_K/(6*pi*probe_radius*(p_peri_fit_ci(1)/(4*delta_t)*1e-3)*1e-12)*1e3; %cP (centipoise, mPa⋅s)

[p_simu_core,p_fit_core,...
    ~,~,~,~] =...
    In_Nuc_fit(Step_in_Core_simu,Step_in_Core,...
    pop_core_ratio,slack_Core(1),slack_Core(2),...
    (0:20:1000),["off" , "off"]);
p_core_fit_ci = In_Nuc_fit_ci(Step_in_Core,p_fit_core);

% Physical properties derived from the fit
Diff_core_um2s = p_fit_core(2) / (4*delta_t) * 1e-3;            % µm²/s
Vis_core    = 1.380649e-23*temp_K / (6*pi*probe_radius* ...
                   Diff_core_um2s * 1e-12) * 1e3;          % cP
Vis_core_lb = 1.380649e-23*temp_K/(6*pi*probe_radius*(p_core_fit_ci(2)/(4*delta_t)*1e-3)*1e-12)*1e3; %cP (centipoise, mPa⋅s)
Vis_core_ub = 1.380649e-23*temp_K/(6*pi*probe_radius*(p_core_fit_ci(1)/(4*delta_t)*1e-3)*1e-12)*1e3; %cP (centipoise, mPa⋅s)

end