<<<<<<< HEAD
function [Vis_nuc,Vis_nuc_lb,Vis_nuc_ub,Vis_cyto,Vis_cyto_lb,Vis_cyto_ub] =...
    CalVis_Nuc_Cyto(delta_t,temp_K,probe_radius,acc_fit,Ro,Lo,anchor_spMap,spMap,...
    scaling_width,scaling_length,num_pix_y,aspt_ratio,nuc_outline_sp,...
    raw_spatialDisp,Simu_spatialDisp,coord_in_nuc,coord_in_cyto,slack_Nuc)

pop_nuc_ratio =...
    Pop_Nuc_Ratio(5e5,acc_fit,Ro,Lo,anchor_spMap,...
    scaling_width,scaling_length,num_pix_y,...
    aspt_ratio,nuc_outline_sp);

[Step_in_Nuc,~] =...
    Extract_Step_InRegion(raw_spatialDisp,...
    coord_in_nuc,num_pix_y,aspt_ratio);

[Step_in_Nuc_simu,~] =...
    Extract_Step_InRegion(Simu_spatialDisp,...
    coord_in_nuc,num_pix_y,aspt_ratio);

[p_simu,p_fit,~,~,~,~] =...
    In_Nuc_fit(Step_in_Nuc_simu,Step_in_Nuc,...
    pop_nuc_ratio,slack_Nuc(1),slack_Nuc(2),...
    (0:20:1000),["off" "off"]);
% compute error bar by nonlinear fitting parameter confidence interval
p_nuc_fit_ci = In_Nuc_fit_ci(Step_in_Nuc,p_fit);

% Physical properties derived from the fit
Diff_nuc_um2s = p_fit(2) / (4*delta_t) * 1e-3;            % µm²/s
Vis_nuc    = 1.380649e-23*temp_K / (6*pi*probe_radius* ...
                   Diff_nuc_um2s * 1e-12) * 1e3;          % cP
Vis_nuc_lb = 1.380649e-23*temp_K/(6*pi*probe_radius*(p_nuc_fit_ci(2)/(4*delta_t)*1e-3)*1e-12)*1e3; %cP (centipoise, mPa⋅s)
Vis_nuc_ub = 1.380649e-23*temp_K/(6*pi*probe_radius*(p_nuc_fit_ci(1)/(4*delta_t)*1e-3)*1e-12)*1e3; %cP (centipoise, mPa⋅s)

[p_cyto_fit,p_cyto_fit_ci,~] =...
    In_Cyto_fit(raw_spatialDisp,spMap,...
    coord_in_cyto,aspt_ratio,num_pix_y,...
    (0:20:1000),"off", "off");
Diff_cyto = p_cyto_fit(1)/(4*delta_t)*1e-3;  % um^2/s
Diff_cyto_lb = p_cyto_fit_ci(1)/(4*delta_t)*1e-3; 
Diff_cyto_ub = p_cyto_fit_ci(2)/(4*delta_t)*1e-3;  
Vis_cyto = 1.380649e-23*temp_K/(6*pi*probe_radius*Diff_cyto*1e-12)*1e3; %cP (centipoise, mPa⋅s)
Vis_cyto_lb = 1.380649e-23*temp_K/(6*pi*probe_radius*Diff_cyto_ub*1e-12)*1e3; 
Vis_cyto_ub = 1.380649e-23*temp_K/(6*pi*probe_radius*Diff_cyto_lb*1e-12)*1e3;

=======
function [Vis_nuc,Vis_nuc_lb,Vis_nuc_ub,Vis_cyto,Vis_cyto_lb,Vis_cyto_ub] =...
    CalVis_Nuc_Cyto(delta_t,temp_K,probe_radius,acc_fit,Ro,Lo,anchor_spMap,spMap,...
    scaling_width,scaling_length,num_pix_y,aspt_ratio,nuc_outline_sp,...
    raw_spatialDisp,Simu_spatialDisp,coord_in_nuc,coord_in_cyto,slack_Nuc)

pop_nuc_ratio =...
    Pop_Nuc_Ratio(5e5,acc_fit,Ro,Lo,anchor_spMap,...
    scaling_width,scaling_length,num_pix_y,...
    aspt_ratio,nuc_outline_sp);

[Step_in_Nuc,~] =...
    Extract_Step_InRegion(raw_spatialDisp,...
    coord_in_nuc,num_pix_y,aspt_ratio);

[Step_in_Nuc_simu,~] =...
    Extract_Step_InRegion(Simu_spatialDisp,...
    coord_in_nuc,num_pix_y,aspt_ratio);

[p_simu,p_fit,~,~,~,~] =...
    In_Nuc_fit(Step_in_Nuc_simu,Step_in_Nuc,...
    pop_nuc_ratio,slack_Nuc(1),slack_Nuc(2),...
    (0:20:1000),["off" "off"]);
% compute error bar by nonlinear fitting parameter confidence interval
p_nuc_fit_ci = In_Nuc_fit_ci(Step_in_Nuc,p_fit);

% Physical properties derived from the fit
Diff_nuc_um2s = p_fit(2) / (4*delta_t) * 1e-3;            % µm²/s
Vis_nuc    = 1.380649e-23*temp_K / (6*pi*probe_radius* ...
                   Diff_nuc_um2s * 1e-12) * 1e3;          % cP
Vis_nuc_lb = 1.380649e-23*temp_K/(6*pi*probe_radius*(p_nuc_fit_ci(2)/(4*delta_t)*1e-3)*1e-12)*1e3; %cP (centipoise, mPa⋅s)
Vis_nuc_ub = 1.380649e-23*temp_K/(6*pi*probe_radius*(p_nuc_fit_ci(1)/(4*delta_t)*1e-3)*1e-12)*1e3; %cP (centipoise, mPa⋅s)

[p_cyto_fit,p_cyto_fit_ci,~] =...
    In_Cyto_fit(raw_spatialDisp,spMap,...
    coord_in_cyto,aspt_ratio,num_pix_y,...
    (0:20:1000),"off", "off");
Diff_cyto = p_cyto_fit(1)/(4*delta_t)*1e-3;  % um^2/s
Diff_cyto_lb = p_cyto_fit_ci(1)/(4*delta_t)*1e-3; 
Diff_cyto_ub = p_cyto_fit_ci(2)/(4*delta_t)*1e-3;  
Vis_cyto = 1.380649e-23*temp_K/(6*pi*probe_radius*Diff_cyto*1e-12)*1e3; %cP (centipoise, mPa⋅s)
Vis_cyto_lb = 1.380649e-23*temp_K/(6*pi*probe_radius*Diff_cyto_ub*1e-12)*1e3; 
Vis_cyto_ub = 1.380649e-23*temp_K/(6*pi*probe_radius*Diff_cyto_lb*1e-12)*1e3;

>>>>>>> 5e4cf7b (Initial commit)
end