function [Vis_domain,Vis_domain_lb,Vis_domain_ub] =...
    CalVis_MacroDomain(...
    delta_t,temp_K,probe_radius,spMap,Domain_outline,nuc_outline,num_pix_y,aspt_ratio,...
    raw_spatialDisp,Simu_spatialDisp,acc_fit,Ro,Lo,anchor_spMap,...
    scaling_width,scaling_length,slack_Domain)

[coord_in_domain,DomCoord] =...
    FindDomainCoord(spMap,Domain_outline,...
    nuc_outline,num_pix_y,aspt_ratio,'off');

[Step_in_Domain,~] = Extract_Step_InRegion(raw_spatialDisp,...
    coord_in_domain,num_pix_y,aspt_ratio);
[Step_in_Domain_simu,~] = Extract_Step_InRegion(Simu_spatialDisp,...
    coord_in_domain,num_pix_y,aspt_ratio);

% weight ratio of macrodomain
pop_domain_ratio =...
    Pop_Domain_Ratio(5e5,acc_fit,Ro,Lo,anchor_spMap,...
    scaling_width,scaling_length,num_pix_y,aspt_ratio,...
    nuc_outline,DomCoord);

[p_simu_dom,p_fit_dom,~,~,~,~] =...
    In_Nuc_fit(Step_in_Domain_simu,Step_in_Domain,...
    pop_domain_ratio,slack_Domain(1),slack_Domain(2),...
    (0:20:1000),["off" "off"]);
p_dom_fit_ci = In_Nuc_fit_ci(Step_in_Domain,p_fit_dom);

% Physical properties derived from the fit
Diff_domain_um2s = p_fit_dom(2) / (4*delta_t) * 1e-3;            % µm²/s
Vis_domain    = 1.380649e-23*temp_K / (6*pi*probe_radius* ...
                   Diff_domain_um2s * 1e-12) * 1e3;          % cP
Vis_domain_lb = 1.380649e-23*temp_K/(6*pi*probe_radius*(p_dom_fit_ci(2)/(4*delta_t)*1e-3)*1e-12)*1e3; %cP (centipoise, mPa⋅s)
Vis_domain_ub = 1.380649e-23*temp_K/(6*pi*probe_radius*(p_dom_fit_ci(1)/(4*delta_t)*1e-3)*1e-12)*1e3; %cP (centipoise, mPa⋅s)

end