function [maskData, trackData, fitsData, resultFolder] = DataLoader(dataFolder)
% DataLoader loads PhaseMask, track, and fits data from a specified folder,
% and automatically creates a results folder with the current date.
%
% INPUT:
% dataFolder - String. Full path of the folder containing data files.
%
% OUTPUT:
% maskData - Cell array. Each cell contains the PhaseMask data loaded
% from a .mat file.
% trackData - Cell array. Each cell contains the track data loaded
% from the corresponding file.
% fitsData - Cell array. Each cell contains the fits data loaded
% from the corresponding file.
%
% This function prompts the user to select files (with interface dialogs)
% for both the mask and track data. The number of files selected for each are
% compared, and if there is a mismatch a warning is issued and only the common
% number (the minimum) of file pairs is processed.
%
% Author: Xiaofeng Dai
% Date: 04/08/2025

%% 1. Verify Input Folder
if ~ischar(dataFolder) && ~isstring(dataFolder)
    error('The input dataFolder must be a character vector or string.');
end
if ~exist(dataFolder, 'dir')
    error('The specified folder "%s" does not exist.', dataFolder);
end

%% 2. Extract and Display Folder Title
% Use fileparts to get the last folder name in the path.
[~, folderTitle] = fileparts(dataFolder);
% Replace underscores with spaces for display purposes.
folderTitle = strrep(folderTitle, '_', ' ');
disp(['Loading data from folder: ', folderTitle]);

%% 3. Select Files for Masks and Tracks

% Prompt the user to select mask files (assumes they have "*PhaseMask.mat" naming)
[maskFileNames, ~] = uigetfile(fullfile(dataFolder, '*PhaseMask.mat'), ...
                               'Select mask files', 'MultiSelect', 'on');
if isequal(maskFileNames, 0)
    error('No mask files were selected. Operation canceled.');
end

% Prompt the user to select track files (assumes they have "*fits.mat" naming)
[trackFileNames, ~] = uigetfile(fullfile(dataFolder, '*fits.mat'), ...
                                'Select track files', 'MultiSelect', 'on');
if isequal(trackFileNames, 0)
    error('No track files were selected. Operation canceled.');
end

% Ensure that the file names are stored in cell arrays (this handles the case
% where only one file is selected; uigetfile returns a char array in that case)
if ~iscell(maskFileNames)
    maskFileNames = {maskFileNames};
end

if ~iscell(trackFileNames)
    trackFileNames = {trackFileNames};
end

% Determine the number of mask and track files selected
numMaskFiles = numel(maskFileNames);
numTrackFiles = numel(trackFileNames);

% Compare the number of files in mask and fit/track.
if numMaskFiles ~= numTrackFiles
    error('The number of mask files (%d) does not match the number of track files (%d). Select files again.', ...
            numMaskFiles, numTrackFiles);
end

numFiles = numMaskFiles;
%% 4. Initialize Output Containers
maskData  = cell(numFiles, 1);
trackData = cell(numFiles, 1);
fitsData  = cell(numFiles, 1);

%% 5. Load Data Files in Parallel
% Using parfor for parallel loading may speed up IO when working with many files.
%
% Each iteration loads:
%   - The mask file (expects a variable named "PhaseMask"). PhaseMasks in
%     mat format converted from segmentation results (by cellpose/omnipose)
%   - The track file (expects variables "tracks" and "fits"). 'tracks' and
%     'fits' are varables from results generated by SMALLLABS used for
%     tracking analysis
parfor i = 1:numFiles
    % Form full paths for mask and track files.
    maskFilePath  = fullfile(dataFolder, maskFileNames{i});
    trackFilePath = fullfile(dataFolder, trackFileNames{i});
    
    % Load PhaseMask from the mask file.
    maskStruct = load(maskFilePath);
    if isfield(maskStruct, 'PhaseMask')
        maskData{i} = maskStruct.PhaseMask;
    else
        warning('File "%s" does not contain a variable named "PhaseMask".', maskFilePath);
        maskData{i} = [];
    end
    
    % Load both 'tracks' and 'fits' from the track file.
    trackStruct = load(trackFilePath, 'tracks', 'fits');
    if isfield(trackStruct, 'tracks')
        trackData{i} = trackStruct.tracks;
    else
        warning('File "%s" does not contain a variable named "tracks".', trackFilePath);
        trackData{i} = [];
    end
    if isfield(trackStruct, 'fits')
        fitsData{i} = trackStruct.fits;
    else
        warning('File "%s" does not contain a variable named "fits".', trackFilePath);
        fitsData{i} = [];
    end
end

%% 6. Create a Result Folder with Today's Date
% Get today's date formatted as yyyy_MM_dd.
todayDate = char(datetime('today', 'Format', 'yyyy_MM_dd'));
resultFolderName = ['Result_', todayDate];
resultFolder = fullfile(dataFolder, resultFolderName);

% Create the folder (mkdir will create it if it does not already exist)
[status, msg, msgID] = mkdir(resultFolder);
if ~status
    warning('Could not create result folder "%s": %s (%s)', resultFolder, msg, msgID);
else
    disp(['Result folder created at: ', resultFolder]);
end
end